### ISSUE TITLE
plot_predictiveness_curve function raises ZeroDivisionError

### ISSUE THREAD

**Issue by yamasakih** [yamasakih/predictiveness-curve#56]
```python
scores = np.array([10, 9, 5, 1, 8, 7, 6, 4, 3, 2])
labels = np.zeros((10, ), dtype='int32')
labels[:4] = 1
    
fig = plot_predictiveness_curve(scores, labels, kind='EF')
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-33-76a20ab8dc06> in <module>()
----> 1 fig = plot_predictiveness_curve(scores, labels, kind='EF')

~/repositories/predictiveness-curve/predictiveness_curve/base.py in plot_predictiveness_curve(risks, labels, classes, normalize, points, figsize, fontsize, kind, xlabel, top_ylabel, bottom_ylabel, **kwargs)
    155         enrichment_factors = calculate_enrichment_factor(risks,
    156                                                          labels,
--> 157                                                          threshold=thresholds)
    158         _set_axes(ax, lim, fontsize)
    159         ax.plot(thresholds, enrichment_factors, **kwargs)

~/repositories/predictiveness-curve/predictiveness_curve/base.py in calculate_enrichment_factor(scores, labels, classes, threshold)
    226 
    227     _calculate_enrichment_factor = np.frompyfunc(f, 1, 1)
--> 228     return _calculate_enrichment_factor(threshold)
    229 
    230 

~/repositories/predictiveness-curve/predictiveness_curve/base.py in f(threshold)
    197     def f(threshold):
    198         n = int(np.floor(scores.size * threshold))
--> 199         return (np.count_nonzero(labels[-n:]) / n) / positive_ratio
    200 
    201     scores = np.array(scores)
```

**Comment by yamasakih** [comment]
Closes #51

**Comment by yamasakih** [comment]
`f` function that is further called by `calculate_enrichment_factor` function that is internally called was the cause of the error.

**Comment by yamasakih** [comment]
Variable `n` became zero when `scores` size and `threshold` were very small.

```python
    def f(threshold):
        n = int(np.floor(scores.size * threshold))
        return (np.count_nonzero(labels[-n:]) / n) / positive_ratio
```

Then, divided error was raised because `n` = 0.

**Comment by yamasakih** [comment]
Should it raise ValueError or return value one for enrichment factor?

**Comment by yamasakih** [comment]
I asked my cat friend @tonets :cat: how should I handle them, then I decided how to implement them like below:

* [x] `calculate_enrichment_factor` function returns one and warning.
* [ ] `plot_predictiveness_curve` function returns the plot which doesn't contain warning one value.

Ref. https://twitter.com/yamasaKit_/status/1150195337551732738 (Japanese)

**Comment by tonets** [comment]
😸

**Comment by yamasakih** [comment]
warnings.warn can output warning.  Ref. https://pod.hatenablog.com/entry/2017/06/11/180837

**Comment by yamasakih** [comment]
pytest can check if warning is output by using  pytest.warns like below:

```python
def test_warning():
    with pytest.warns(UserWarning):
        warnings.warn("my warning", UserWarning)
```

Ref. https://docs.pytest.org/en/3.0.4/recwarn.html#asserting-warnings

**Comment by yamasakih** [comment]
`numpy.frompyfunc` returns values whose dtype is only object?

Bugfix `_calculate_enrichment_factors` function by adding `.astype('float32')` to returned value.

**Comment by yamasakih** [comment]
It became a bit redundant, so I will improve it someday.

```python
_calculate_enrichment_factor = np.frompyfunc(f, 1, 1)
enrichment_factors = _calculate_enrichment_factor(threshold)
if isinstance(enrichment_factors, float):
    if enrichment_factors is np.nan:
        enrichment_factors = 1
        warnings.warn(
            'Returns one as the value of enrichment factor because the '
           'product of sample data and threshold is less than one')
elif isinstance(enrichment_factors, np.ndarray):
    enrichment_factors = enrichment_factors.astype('float32')
    if np.any(np.isnan(enrichment_factors)):
        warnings.warn(
            'Returns one as the value of enrichment factor because the '
            'product of sample data and threshold is less than one')
        enrichment_factors[np.isnan(enrichment_factors)] = 1
```

**Comment by yamasakih** [comment]
`calculate_enrichment_factor` function will raise the warning if the product of data size and threshold is less than one. https://github.com/yamasakih/predictiveness-curve/pull/51/commits/caa5e84a9cb684c480b70df37af592cba6565c23

**Comment by yamasakih** [comment]
Refactored code. https://github.com/yamasakih/predictiveness-curve/pull/51/commits/cbf002bf00fcbc7ed04ee713ddd906a3e713fa23

Ref. https://github.com/yamasakih/predictiveness-curve/issues/56#issuecomment-511201562.

**Comment by yamasakih** [comment]
`plot_predictiveness_curve` function returns the plot which doesn't contain warning one value and 
outputs warning. https://github.com/yamasakih/predictiveness-curve/pull/51/commits/28f78b961d65ff8482cfd90db04892f537f1633e

**Comment by yamasakih** [comment]
It worked. Thx @tonets 😼
